language: node_js
node_js:
  - "11.8"

script:
  - mkdir travis-build
  - cd travis-build
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - ./emsdk install latest-upstream
  - ./emsdk activate latest-upstream
  - source ./emsdk_env.sh
  - cd ..
  - emcmake cmake ..
  - make
  - mkdir ../build
  - cp wdosbox.* ../build
  - npm install -g gulp
  - npm install
  - gulp
