# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            js-dos
tagline:          'Dosbox for browser'
description:      'A javascript version of dosbox that can run dos programs and games in browser. Made by <a href="https://twitter.com/caiiiycuk" target="_blank">@caiiiycuk</a>'
url:              'https://github.com/caiiiycuk/js-dos.com'
baseurl:          '/js-dos.com'

excerpt_separator: <!--more-->

author:
  name:           'Aleksander Gyranov'
  url:            https://twitter.com/caiiiycuk

paginate:         10

# Custom vars
version:          0.0.beta

github:
  repo:           https://github.com/caiiiycuk/js-dos.com
